// client/src/components/Register.jsx
import React, { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { useHistory } from 'react-router-dom';
import Loading from './Loading';
const Register = () => {

  const [isLoading, setIsLoading] = useState(false);

  const history = useHistory();

  const { login } = useAuth();

  const [formData, setFormData] = useState({
    username: '',
    password: '',
    class_: 'Warrior',
  });

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsLoading(true)
    try {
      const response = await fetch('/character', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },  
        body: JSON.stringify(formData),
        credentials: 'include',
      });
      setIsLoading(false)
      if (response.ok) {
        login();
        history.push('/play');
      } else {
        console.error('Registration failed:', response.statusText);
      }
    } catch (error) {
      console.error('Error during registration:', error.message);
    }
  };

  return (
    <div className="container mx-auto mt-8 px-10 py-5">
      <h2 className="text-2xl font-bold mb-4">Register</h2>
      <form onSubmit={handleSubmit} className="max-w-md">
        <div className="mb-4">
          <label htmlFor="username" className="block text-sm font-medium text-gray-700">
            Username
          </label>
          <input
            type="text"
            id="username"
            name="username"
            value={formData.username}
            onChange={handleChange}
            required
            className="mt-1 p-2 border border-gray-300 rounded-md w-full"
          />
        </div>
        <div className="mb-4">
          <label htmlFor="password" className="block text-sm font-medium text-gray-700">
            Password
          </label>
          <input
            type="password"
            id="password"
            name="password"
            value={formData.password}
            onChange={handleChange}
            required
            className="mt-1 p-2 border border-gray-300 rounded-md w-full"
          />
        </div>
        <div className="mb-4">
          <label htmlFor="class_" className="block text-sm font-medium text-gray-700">
            Class
          </label>
          <select
            id="class_"
            name="class_"
            value={formData.class_}
            onChange={handleChange}
            className="mt-1 p-2 border border-gray-300 rounded-md w-full"
          >
            <option value="Warrior">Warrior</option>
            <option value="Mage">Mage</option>
            <option value="Archer">Archer</option>
            <option value="Cleric">Cleric</option>
            <option value="Warlock">Warlock</option>
            <option value="Paladin">Paladin</option>
          </select>
        </div>
        <button
          type="submit"
          className="w-full bg-blue-500 text-white p-2 rounded-md hover:bg-blue-600"
        >
          Register
        </button>
      </form>
      {isLoading && <Loading/>}
    </div>
  );
};

export default Register;

// client/src/routes/register/+page.svelte
<script>
	  import { goto } from '$app/navigation';
    import classesData from '$lib/data/classes.json';
    import virtuesData from '$lib/data/virtues.json';
    import flawsData from '$lib/data/flaws.json';
    import toast from 'svelte-french-toast';
    import LoadingSpinner from '../../components/common/LoadingSpinner.svelte';
    import { initializeCharacterData } from '$lib/stores/characterData'

    let classes = Object.keys(classesData);
    let flaws = Object.keys(flawsData);
    let virtues = Object.keys(virtuesData);

    let username = '';
    let password = '';
    let selectedClass = '';
    let selectedVirtue = '';
    let selectedFlaw = '';

    let isLoading = false;

    const handleSubmit = async (event) => {
      isLoading = true;
      try {
      const formData ={
        "username": username.toLowerCase(),
        "password": password.toLowerCase(),
        "class_":selectedClass.toLowerCase(),
        "virtue":selectedVirtue.toLowerCase(),
        "flaw":selectedFlaw.toLowerCase(),
      };
      const response = await fetch('http://localhost:8000/api/character/create', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(formData),
        credentials: 'include'
      });

      const responseData = await response.json();

      isLoading = false;

      if (response.ok) {
        isLoading = true;
        initializeCharacterData()
        isLoading= false;
        toast.success('Character created successfully: ', responseData);
        goto("/play")
        
      } else {
        toast.error(responseData.detail);

      }
      } catch (error) {
        toast.error(error.message);
        console.log('Registration failed:', error)
      }
    };

  </script>
  
  <div class="container mx-auto px-10 py-5 text-gray-600 text-xl ">
    <h1 class="text-2xl font-bold mb-4">Character Creation</h1>
    <form class="w-50" on:submit|preventDefault={handleSubmit}>
      <div class="mb-4">
        <label for="username" class="block text-sm font-bold mb-2">Character Name:</label>
        <input type="text" id="username" bind:value={username} class="border p-2 lg:w-[20vw] w-[50vw]" />
      </div>
  
      <div class="mb-4">
        <label for="password" class="block text-sm font-bold mb-2">Password:</label>
        <input type="password" id="password" bind:value={password} class="border p-2 lg:w-[20vw] w-[50vw]" />
      </div>
      <div class="flex flex-col justify-between">
        <div class="mb-4">
            <label for="class" class="block text-sm font-bold mb-2">Class:</label>
            <select id="class" bind:value={selectedClass} class="border p-2 lg:w-[12vw] w-[30vw]">
            {#each classes as className (className)}
                <option value={className}>{className}</option>
            {/each}
            </select>
        </div>

        <div class="mb-4">
            <label for="virtue" class="block text-sm font-bold mb-2">Virtue:</label>
            <select id="virtue" bind:value={selectedVirtue} class="border p-2 lg:w-[12vw] w-[30vw]">
            {#each virtues as virtueName (virtueName)}
                <option value={virtueName}>{virtueName}</option>
            {/each}
            </select>
        </div>

        <div class="mb-4">
            <label for="flaw" class="block text-sm font-bold mb-2">Flaw:</label>
            <select id="flaw" bind:value={selectedFlaw} class="border p-2 lg:w-[12vw] w-[30vw]">
            {#each flaws as flawName (flawName)}
                <option value={flawName}>{flawName}</option>
            {/each}
            </select>
        </div>
        
      </div>
      {#if (isLoading === true)}
      <LoadingSpinner/>
      {/if}
      <button type="submit" class="bg-blue-500 text-white py-2 px-4 mb-10 rounded">Create Character</button>
    </form>
  </div>
