// client/src/routes/login/+page.svelte
<script>
	import { goto } from '$app/navigation';
    import LoadingSpinner from "../../components/common/LoadingSpinner.svelte";
    import toast from "svelte-french-toast";
    import { initializeCharacterData } from "../../lib/stores/characterData";

    let username;
    let password;
    let isLoading = false;

    const handleSubmit = async (event) => {
      isLoading = true;
      try {
        const formData = new URLSearchParams();

        formData.append('username', username);
        formData.append('password', password);

        const response = await fetch('http://localhost:8000/api/auth/login', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
            },
            body: formData.toString(),
            credentials: 'include'
        });

        const responseData = await response.json();

        isLoading = false;

        if (response.ok) {
            isLoading = true;
            initializeCharacterData()
            isLoading= false;
            toast.success('Logged in succesfuly: ', responseData);
            goto("/play")
            
        } else {
            toast.error(responseData.detail);

        }
        } catch (error) {
            isLoading = false;
            toast.error(error.message);
            console.log('Login failed:', error)
        }
    };

</script>


<div class="container mx-auto px-10 py-5 text-gray-600 text-xl ">
    <h1 class="text-2xl font-bold mb-4">Character Creation</h1>
    <form class="w-50" on:submit|preventDefault={handleSubmit}>
      <div class="mb-4">
        <label for="username" class="block text-sm font-bold mb-2">Character Name:</label>
        <input type="text" id="username" bind:value={username} class="border p-2 lg:w-[20vw] w-[50vw]" />
      </div>
  
      <div class="mb-4">
        <label for="password" class="block text-sm font-bold mb-2">Password:</label>
        <input type="password" id="password" bind:value={password} class="border p-2 lg:w-[20vw] w-[50vw]" />
      </div>
      <div class="flex flex-col justify-between">
        
      </div>
      {#if (isLoading === true)}
        <LoadingSpinner/>
      {/if}
      <button type="submit" class="bg-blue-500 text-white py-2 px-4 mb-10 rounded">Log in</button>
    </form>
  </div>

// client/src/components/Login.jsx
import React, { useState } from 'react';
import { Link, useHistory } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import   Loading   from './Loading';

const Login = () => {
  const [isLoading, setIsLoading] = useState(false);
  const history = useHistory();
  const { login } = useAuth();
  const [formData, setFormData] = useState({
    username: '',
    password: '',
  });

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
  
    try {
      setIsLoading(true);

      const response = await fetch('/auth/', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: new URLSearchParams(formData).toString(),
        credentials: 'include',
      });

      setIsLoading(false);

      if (response.ok) {
        login();
        history.push('/play');
      } else {
        console.error('Login failed:', response.statusText);
      }
    } catch (error) {
      console.error('Error during login:', error.message);
    }
  };

  return (
    <div className="container mx-auto mt-8 px-10 py-5">
      <h2 className="text-2xl font-bold mb-4">Login</h2>
      <form onSubmit={handleSubmit} className="max-w-md">
        <div className="mb-4">
          <label htmlFor="username" className="block text-sm font-medium text-gray-700">
            Username
          </label>
          <input
            type="text"
            id="username"
            name="username"
            value={formData.username}
            onChange={handleChange}
            required
            className="mt-1 p-2 border border-gray-300 rounded-md w-full"
          />
        </div>
        <div className="mb-4">
          <label htmlFor="password" className="block text-sm font-medium text-gray-700">
            Password
          </label>
          <input
            type="password"
            id="password"
            name="password"
            value={formData.password}
            onChange={handleChange}
            required
            className="mt-1 p-2 border border-gray-300 rounded-md w-full"
          />
        </div>
        <button
          type="submit"
          className="w-full bg-blue-500 text-white p-2 rounded-md hover:bg-blue-600"
        >
          Login
        </button>
      </form>
      <div className="mt-4">
        <p>
          Don't have an account? <Link to="/register">Register here</Link>.
        </p>
      </div>
      {isLoading && <Loading />}
    </div>
  );
};

export default Login;
